export interface Question {
  id: number;
  code: string;
  text: string;
  options: string[];
  correctIndex: number;
  difficulty: "ŁATWE" | "ŚREDNIE" | "TRUDNE" | "MEGA TRUDNE";
}

export const QUESTIONS: Question[] = [
  {
    id: 1,
    code: "Pytanie1",
    text: "Kiedy urodził się biskup Władysław Goral?",
    options: ["15 sierpnia 1903 r.", "1 maja 1898 r.", "3 marca 1890 r."],
    correctIndex: 1,
    difficulty: "ŁATWE",
  },
  {
    id: 2,
    code: "Pytanie2",
    text: "W jakim mieście Goral pełnił funkcję biskupa pomocniczego?",
    options: ["Kraków", "Warszawa", "Lublin"],
    correctIndex: 2,
    difficulty: "ŁATWE",
  },
  {
    id: 3,
    code: "Pytanie3",
    text: "Przez jakiego papieża Goral został beatyfikowany i w którym roku?",
    options: ["Benedykt XVI, 2005 r.", "Jan XXIII, 1963 r.", "Jan Paweł II, 1999 r."],
    correctIndex: 2,
    difficulty: "ŁATWE",
  },
  {
    id: 4,
    code: "Pytanie4",
    text: "W jakim obozie koncentracyjnym więziony był bp Goral i ile czasu tam spędził?",
    options: ["Dachau, przez 2 lata", "Sachsenhausen, około 5 lat", "Auschwitz, przez 3 lata"],
    correctIndex: 1,
    difficulty: "ŚREDNIE",
  },
  {
    id: 5,
    code: "Pytanie5",
    text: "Jak nazywała się niemiecka akcja, w ramach której aresztowano biskupa?",
    options: ["Sonderaktion Lublin, 17 listopada 1939 r.", "Aktion Reinhardt, 5 marca 1940 r.", "Unternehmen Barbarossa, 22 czerwca 1941 r."],
    correctIndex: 0,
    difficulty: "ŚREDNIE",
  },
  {
    id: 6,
    code: "Pytanie6",
    text: "Gdzie Goral studiował i jaki stopień naukowy zdobył?",
    options: ["Teologię w Krakowie – licencjat", "Prawo kanoniczne w Paryżu – doktorat", "Filozofię w Rzymie – doktorat; teologię we Fryburgu szwajcarskim – licencjat"],
    correctIndex: 2,
    difficulty: "ŚREDNIE",
  },
  {
    id: 7,
    code: "Pytanie7",
    text: "Jakie numery obozowe nosił bp Goral w Sachsenhausen?",
    options: ["Najpierw 5605, od 1943 roku – 13981", "Jeden numer: 7777 przez cały pobyt", "Najpierw 1234, od 1942 roku – 9999"],
    correctIndex: 0,
    difficulty: "TRUDNE",
  },
  {
    id: 8,
    code: "Pytanie8",
    text: "Jakie organizacje tworzył lub współtworzył bp Goral z myślą o robotnikach?",
    options: ["Polskie Towarzystwo Gimnastyczne, Związek Strzelecki", "Chrześcijańskie Zjednoczenie Zawodowe RP, Chrześcijański Uniwersytet Robotniczy, Lubelskie Towarzystwo Dobroczynności", "Towarzystwo Czytelni Ludowych, Klub Sportowy Lublinianka"],
    correctIndex: 1,
    difficulty: "TRUDNE",
  },
  {
    id: 9,
    code: "Pytanie9",
    text: "Jakim odznaczeniem uhonorowano biskupa pośmiertnie i w którym roku?",
    options: ["Orderem Orła Białego, 1947 r.", "Krzyżem Komandorskim z Gwiazdą Orderu Odrodzenia Polski, 16 kwietnia 1949 r.", "Krzyżem Virtuti Militari, 1946 r."],
    correctIndex: 1,
    difficulty: "TRUDNE",
  },
  {
    id: 10,
    code: "Pytanie10",
    text: "Co wynikało z zeznań palacza z KL Sachsenhausen odnalezionych w 2022 r. przez Pawła Woźniaka?",
    options: ["Biskup Goral zbiegł z obozu i ukrywał się aż do wyzwolenia", "Bp Goral został wywieziony tuż przed ewakuacją Sachsenhausen do KL Ravensbrück", "Biskup Goral zmarł na chorobę w szpitalu obozowym in 1943 r."],
    correctIndex: 1,
    difficulty: "MEGA TRUDNE",
  },
  {
    id: 11,
    code: "Pytanie11",
    text: "Z jakiej rodziny pochodził Władysław Goral?",
    options: ["Ze szlacheckiej, zamożnej rodziny ziemiańskiej", "Z mieszczańskiej rodziny kupieckiej", "Z chłopskiej, pobożnej rodziny"],
    correctIndex: 2,
    difficulty: "ŁATWE",
  },
  {
    id: 12,
    code: "Pytanie12",
    text: "Gdzie Goral ukończył szkołę powszechną?",
    options: ["W Lublinie", "W Nasutowie", "W Lubartowie"],
    correctIndex: 1,
    difficulty: "ŁATWE",
  },
  {
    id: 13,
    code: "Pytanie13",
    text: "Jaką funkcję pełnił Goral w seminarium duchownym po powrocie do Lublina w 1926 r.?",
    options: ["Rektora seminarium", "Kapelana wojskowego", "Profesora (wykładowcy)"],
    correctIndex: 2,
    difficulty: "ŁATWE",
  },
  {
    id: 14,
    code: "Pytanie14",
    text: "Jaki był pierwszy wyrok wydany na biskupa Gorala po aresztowaniu i jak go zmieniono?",
    options: ["Skazano go na 10 lat więzienia, potem zwolniono", "Zaocznie skazano na śmierć, potem zamieniono wyrok na dożywotnie więzienie", "Skazano go na przymusowe roboty, potem przeniesiono do obozu"],
    correctIndex: 1,
    difficulty: "ŚREDNIE",
  },
  {
    id: 15,
    code: "Pytanie15",
    text: "Jaką jedyną formę kontaktu ze światem zewnętrznym miał bp Goral w obozie?",
    options: ["Cotygodniowe wizyty kapelana obozowego", "Słuchanie radia przez strażników", "Cenzurowane listy wysyłane dwa razy w miesiącu"],
    correctIndex: 2,
    difficulty: "ŚREDNIE",
  },
  {
    id: 16,
    code: "Pytanie16",
    text: "Jakim tytularnym biskupstwem obdarzono Gorala przy mianowaniu go biskupem pomocniczym?",
    options: ["Biskupem tytularnym Kartaginy", "Biskupem tytularnym Maloe in Isauria", "Biskupem tytularnym Aleksandrii"],
    correctIndex: 1,
    difficulty: "ŚREDNIE",
  },
  {
    id: 17,
    code: "Pytanie17",
    text: "Kto udzielił bp. Goralowi święceń biskupich w 1938 r. i gdzie się to odbyło?",
    options: ["Prymas Polski w Warszawie, bp Hlond i dwóch biskupów", "W katedrze lubelskiej; bp Fulman, bp Niemira i bp Tomczak", "W Watykanie, osobiście przez papieża Piusa XI"],
    correctIndex: 1,
    difficulty: "TRUDNE",
  },
  {
    id: 18,
    code: "Pytanie18",
    text: "Jaką gazetę redagował bp Goral przed aresztowaniem?",
    options: ["Tygodnik Powszechny", "Głos Lubelski", "Wiadomości Diecezjalne Lubelskie"],
    correctIndex: 2,
    difficulty: "TRUDNE",
  },
  {
    id: 19,
    code: "Pytanie19",
    text: "Czym w obozie zasłynął bp Goral według wspomnień współwięźniów?",
    options: ["Organizowaniem tajnych nabożeństw dla całego obozu", "Pogodnym obliczem i godnością mimo izolacji i cierpienia", "Ucieczką i ponownym schwytaniem przez Niemców"],
    correctIndex: 1,
    difficulty: "TRUDNE",
  },
  {
    id: 20,
    code: "Pytanie20",
    text: "Który papież wysłał bp. Gorala na studia do Rzymu i jaka była jego rola w tym momencie?",
    options: ["Papież Pius XII mianował go swoim osobistym wysłannikiem", "Ówczesny bp lubelski Marian Fulman wysłał go jako diakona na studia filozoficzne", "Papież Benedykt XV wezwał go osobiście do Watykanu jako doktoranta prawo"],
    correctIndex: 1,
    difficulty: "MEGA TRUDNE",
  },
];
